import { Copy, Download, Printer } from "lucide-react";
import { asArray, asRecord, safeJsonDownload, toText } from "../../utils/formatters";
import { Button } from "../ui/Button";
import { Card } from "../ui/Card";
import { RiskBadge } from "../ui/RiskBadge";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
    <h3 className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">{title}</h3>
    {children}
  </section>
);

export function DoctorReportView({ report }: { report: Record<string, unknown> }) {
  const profile = asRecord(report.user_profile ?? report.profile ?? report.user);
  const vitals = asRecord(report.latest_vitals_summary ?? report.latest_vitals ?? report.vitals);
  const labs = asRecord(report.latest_lab_summary ?? report.lab_summary ?? report.labs);
  const risks = asRecord(report.latest_risk_scores ?? report.risk_scores ?? report.risks);
  const factors = asArray(report.top_risk_factors ?? report.risk_factors);
  const alerts = asArray(report.recent_alerts ?? report.alerts);
  const preventivePlan = asRecord(report.preventive_plan ?? report.plan);
  const plan = asArray(preventivePlan.daily_routine ?? report.preventive_plan ?? report.plan);

  const copySummary = async () => {
    const summary = [
      `LifeTwin AI Doctor Summary for ${toText(profile.full_name ?? profile.name, "Demo Patient")}`,
      `Risk: ${toText(report.overall_risk_level ?? risks.overall, "moderate")}`,
      `Top factors: ${factors.map((item) => toText(asRecord(item).factor ?? item, "")).filter(Boolean).join(", ")}`,
      `Plan: ${plan.map((item) => toText(item, "")).filter(Boolean).join("; ")}`,
    ].join("\n");
    await navigator.clipboard.writeText(summary);
  };

  return (
    <Card
      className="print:border-0 print:bg-white print:text-slate-950"
      title={
        <div>
          <h1 className="text-2xl font-bold text-white print:text-slate-950">Preventive Health Report</h1>
          <p className="text-sm text-slate-400 print:text-slate-600">Generated by LifeTwin AI for clinician review.</p>
        </div>
      }
      action={
        <div className="flex flex-wrap gap-2 print:hidden">
          <Button variant="secondary" onClick={() => window.print()}>
            <Printer size={16} /> Print
          </Button>
          <Button variant="secondary" onClick={copySummary}>
            <Copy size={16} /> Copy Summary
          </Button>
          <Button variant="secondary" onClick={() => safeJsonDownload("lifetwin-doctor-report.json", report)}>
            <Download size={16} /> Download JSON
          </Button>
        </div>
      }
    >
      <div className="grid gap-4 md:grid-cols-2">
        <Section title="User Profile">
          <dl className="space-y-2 text-sm">
            {["name", "age", "gender", "target_age"].map((key) => (
              <div key={key} className="flex justify-between gap-4">
                <dt className="text-slate-400">{key}</dt>
                <dd className="font-medium text-white print:text-slate-950">{toText(key === "name" ? profile.full_name ?? profile.name : profile[key], key === "name" ? "Demo Patient" : "N/A")}</dd>
              </div>
            ))}
          </dl>
        </Section>
        <Section title="Latest Vitals">
          <dl className="grid grid-cols-2 gap-2 text-sm">
            {Object.entries(Object.keys(vitals).length ? vitals : { heart_rate: 72, spo2: 98, sleep_hours: 6.7, bmi: 26.1 }).map(([key, value]) => (
              <div key={key} className="rounded-xl bg-white/[0.04] p-3">
                <dt className="text-slate-400">{key.replace(/_/g, " ")}</dt>
                <dd className="font-semibold text-white print:text-slate-950">{toText(value)}</dd>
              </div>
            ))}
          </dl>
        </Section>
        <Section title="Lab Summary">
          <dl className="grid grid-cols-2 gap-2 text-sm">
            {Object.entries(Object.keys(labs).length ? labs : { ldl: "132 mg/dL", hba1c: "5.7%", fasting_glucose: "104 mg/dL" }).map(([key, value]) => (
              <div key={key} className="rounded-xl bg-white/[0.04] p-3">
                <dt className="text-slate-400">{key.replace(/_/g, " ")}</dt>
                <dd className="font-semibold text-white print:text-slate-950">{toText(value)}</dd>
              </div>
            ))}
          </dl>
        </Section>
        <Section title="Risk Scores">
          <div className="space-y-2">
            {Object.entries(Object.keys(risks).length ? risks : { cardio: 42, metabolic: 55, sleep: 63 })
              .filter(([, value]) => typeof value === "number" || ["low", "moderate", "high", "critical"].includes(String(value).toLowerCase()))
              .map(([key, value]) => (
              <div key={key} className="flex items-center justify-between rounded-xl bg-white/[0.04] px-3 py-2">
                <span className="text-sm text-slate-300">{key.replace(/_/g, " ")}</span>
                <RiskBadge level={typeof value === "string" ? value : Number(value) > 65 ? "high" : Number(value) > 45 ? "moderate" : "low"} />
              </div>
            ))}
          </div>
        </Section>
      </div>

      <div className="mt-4 grid gap-4 md:grid-cols-3">
        <Section title="Top Risk Factors">
          <ul className="space-y-2 text-sm text-slate-300">
            {(factors.length ? factors : ["Sleep inconsistency", "Low walking volume", "LDL/metabolic risk"]).map((item, index) => (
              <li key={index}>{toText(asRecord(item).factor ?? item, "Risk factor")}</li>
            ))}
          </ul>
        </Section>
        <Section title="Recent Alerts">
          <ul className="space-y-2 text-sm text-slate-300">
            {(alerts.length ? alerts : ["Moderate sleep debt alert", "Activity recovery improving"]).map((item, index) => (
              <li key={index}>{toText(asRecord(item).title ?? item, "Alert")}</li>
            ))}
          </ul>
        </Section>
        <Section title="Preventive Plan">
          <ul className="space-y-2 text-sm text-slate-300">
            {(plan.length ? plan : ["Improve sleep regularity", "25-minute post-meal walk", "Follow up lipid/metabolic markers"]).map((item, index) => (
              <li key={index}>{toText(asRecord(item).recommended_action ?? asRecord(item).action ?? item, "Plan item")}</li>
            ))}
          </ul>
        </Section>
      </div>

      <p className="medical-disclaimer mt-5">
        This is a preventive wellness insight, not a medical diagnosis. Please consult a qualified healthcare professional for medical advice.
      </p>
    </Card>
  );
}
